name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.2.4"
          gleam-version: "1.8.1"
          rebar3-version: "3.24.0"
      - run: gleam deps download
      - run: gleam check
      - run: gleam format --check src
